- project:
    templates:
      - check-requirements
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - openstack-python37-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - senlin-dsvm-tempest-py27-api
        - senlin-dsvm-tempest-py35-api
        - senlin-dsvm-tempest-py27-functional
        - senlin-dsvm-tempest-py35-functional
        - senlin-dsvm-tempest-py27-integration:
            voting: false
        - senlin-dsvm-tempest-py35-integration:
            voting: false
        - openstack-tox-cover:
            voting: false
    gate:
      queue: senlin
      jobs:
        - senlin-dsvm-tempest-py27-api
        - senlin-dsvm-tempest-py35-api
        - senlin-dsvm-tempest-py27-functional
        - senlin-dsvm-tempest-py35-functional
    experimental:
      jobs:
        - rally-dsvm-senlin-senlin

- job:
    name: senlin-tempest-base
    parent: devstack-tempest
    description: Senlin Devstack tempest base job
    timeout: 7800
    required-projects:
      - openstack/senlin
      - openstack/senlin-tempest-plugin
    irrelevant-files:
      - ^.*\.rst$
      - ^api-ref/.*$
      - ^doc/.*$
      - ^releasenotes/.*$
    vars:
      tox_envlist: all
      devstack_services:
        tempest: true
      devstack_plugins:
        senlin: https://git.openstack.org/openstack/senlin
      devstack_localrc:
        TEMPEST_PLUGINS: '/opt/stack/senlin-tempest-plugin'
      devstack_local_conf:
        test-config:
          $TEMPEST_CONFIG:
            clustering:
              min_microversion: 1.12
              max_microversion: 1.12

- job:
    name: senlin-dsvm-tempest-py27-api
    parent: senlin-tempest-base
    vars:
      tempest_test_regex: senlin_tempest_plugin.tests.api
      devstack_local_conf:
        post-config:
          $SENLIN_CONF:
             DEFAULT:
               cloud_backend: openstack_test

- job:
    name: senlin-dsvm-tempest-py27-functional
    parent: senlin-tempest-base
    vars:
      tempest_test_regex: senlin_tempest_plugin.tests.functional
      devstack_local_conf:
        post-config:
          $SENLIN_CONF:
            DEFAULT:
              cloud_backend: openstack_test
              health_check_interval_min: 10

- job:
    name: senlin-dsvm-tempest-py27-integration
    parent: senlin-tempest-base
    vars:
      tempest_test_regex: senlin_tempest_plugin.tests.integration
      devstack_plugins:
        zaqar: https://git.openstack.org/openstack/zaqar
        heat: https://git.openstack.org/openstack/heat
      devstack_localrc:
        TEMPEST_PLUGINS: '"/opt/stack/senlin-tempest-plugin /opt/stack/zaqar-tempest-plugin"'
      devstack_local_conf:
        post-config:
          $SENLIN_CONF:
             DEFAULT:
               health_check_interval_min: 10
    required-projects:
      - openstack/heat
      - openstack/octavia
      - openstack/python-zaqarclient
      - openstack/senlin
      - openstack/senlin-tempest-plugin
      - openstack/zaqar
      - openstack/zaqar-ui
      - openstack/zaqar-tempest-plugin

- job:
    name: senlin-dsvm-tempest-py35-api
    parent: senlin-tempest-base
    vars:
      tempest_test_regex: senlin_tempest_plugin.tests.api
      devstack_localrc:
        USE_PYTHON3: true
      devstack_local_conf:
        post-config:
          $SENLIN_CONF:
             DEFAULT:
               cloud_backend: openstack_test

- job:
    name: senlin-dsvm-tempest-py35-functional
    parent: senlin-tempest-base
    vars:
      tempest_test_regex: senlin_tempest_plugin.tests.functional
      devstack_localrc:
        USE_PYTHON3: true
      devstack_local_conf:
        post-config:
          $SENLIN_CONF:
             DEFAULT:
               cloud_backend: openstack_test
               health_check_interval_min: 10

- job:
    name: senlin-dsvm-tempest-py35-integration
    parent: senlin-tempest-base
    vars:
      tempest_test_regex: senlin_tempest_plugin.tests.integration
      devstack_plugins:
        zaqar: https://git.openstack.org/openstack/zaqar
        heat: https://git.openstack.org/openstack/heat
      devstack_localrc:
        USE_PYTHON3: true
        TEMPEST_PLUGINS: '"/opt/stack/senlin-tempest-plugin /opt/stack/zaqar-tempest-plugin"'
      devstack_local_conf:
        post-config:
          $SENLIN_CONF:
             DEFAULT:
               health_check_interval_min: 10
    required-projects:
      - openstack/heat
      - openstack/octavia
      - openstack/python-zaqarclient
      - openstack/senlin
      - openstack/senlin-tempest-plugin
      - openstack/zaqar
      - openstack/zaqar-ui
      - openstack/zaqar-tempest-plugin

- job:
    name: rally-dsvm-senlin-senlin
    parent: senlin-tempest-base
    run: playbooks/legacy/rally-dsvm-senlin-senlin/run.yaml
    post-run: playbooks/legacy/rally-dsvm-senlin-senlin/post.yaml
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/aodh
      - openstack/ceilometer
      - openstack/diskimage-builder
      - openstack/ironic
      - openstack/magnum
      - openstack/networking-bgpvpn
      - openstack/neutron
      - openstack/neutron-fwaas
      - openstack/neutron-lbaas
      - openstack/neutron-vpnaas
      - openstack/octavia
      - openstack/panko
      - openstack/python-magnumclient
      - openstack/python-senlinclient
      - openstack/python-watcherclient
      - openstack/python-zaqarclient
      - openstack/rally
      - openstack/senlin
      - openstack/tripleo-image-elements
      - openstack/watcher
      - openstack/zaqar-ui
