#!/bin/bash

MYSQL_ROOT_PW=openstack
MYSQL_SENLIN_PW=openstack

echo "Recreating 'senlin' database."
cat << EOF | mysql -u root --password=${MYSQL_ROOT_PW}
DROP DATABASE senlin;
CREATE DATABASE senlin DEFAULT CHARACTER SET utf8;
GRANT ALL ON senlin.* TO 'root'@'localhost' IDENTIFIED BY '${MYSQL_SENLIN_PW}';
GRANT ALL ON senlin.* TO 'root'@'%' IDENTIFIED BY '${MYSQL_SENLIN_PW}';
flush privileges;
EOF

